### ISSUE TITLE
proViz DDG error loading file

### ISSUE THREAD

**Issue by kolrocket** [End-to-end-provenance/DDG-Explorer#121]
Hello. I've been trying to study this package's function for my research and I tried to reproduce the help example, i.e.:
  `prov.init(prov.dir = ...) `
  `a <- 1`
  `b <- 2` 
  `prov.save()` 
  `ab <- a + b` 
  `prov.quit() `  

That's ok. But when I try to run the provViz tool:
`prov.visualize.file(prov.file="...")`
When the DDG the error below occurs: Unable to load the file: java.lang.NumberFormatException: For input string: "70,54".

Am I missing something? Thanks.

Edit: The value can be found in "rdt:elapsedTime" line of prov document.

**Comment by blernermhc** [comment]
Given that this is in the elapsedTime field, I am wondering if you are in Europe.  Our parser is expecting to see a . instead of , in that field.

**Comment by kolrocket** [comment]
Oh, I see now! Removing the , solved the problem. Thank you and sorry for delay in response. Also, I'm from Brazil.

**Comment by blernermhc** [comment]
Ok, that is good to know.  We will come up with a solution that avoids the problem, since users should not need to do that, obviously.  So thanks for letting us know!

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/DDG-Explorer/commit/8bf8b58ec1d238e9d2d733616d0143c37e988fd3

**Comment by kolrocket** [comment]
Thank you very much! :)

Em 5 de jun de 2019 15:27, blernermhc <notifications@github.com> escreveu:

Fixed in 8bf8b58<https://github.com/End-to-end-provenance/DDG-Explorer/commit/8bf8b58ec1d238e9d2d733616d0143c37e988fd3>
