### ISSUE TITLE
Unable to save preferences 

### ISSUE THREAD

**Issue by ngohoanglankhanh** [End-to-end-provenance/DDG-Explorer#123]
.ddg folder does not exist. 

![Screen Shot 2019-05-31 at 3 44 50 PM](https://user-images.githubusercontent.com/34677238/58807884-ef94f600-85e6-11e9-8d4d-58f39ed7ee54.png)

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/DDG-Explorer/commit/395a68f52807f765c59298f461f033bf7c701d3f
