### ISSUE TITLE
Right-clicking on start and finish nodes to show code

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/DDG-Explorer#3]
Right-clicking on start and finish nodes (in Windows 7) does not display the intervening source code.  Instead, an error message appears: "Sorry, this code could not be found within the associated script file."  However this feature does work for operational nodes that represent R functions.

**Comment by blernermhc** [comment]
This is partly fixed.  Clicking on start/finish nodes that represent functions should work.

**Comment by blernermhc** [comment]
I think it should also work for start/finish nodes that are created by calls to ddg.start and ddg.finish.
We also automatically create start/finish nodes in RDataTracker to encapsulate calls to functions.  The code that corresponds to these cannot be found currently.  We have talked about putting line numbers in the ddg and doing that would probably make this easy but it will be pretty hard to do within DDG Explorer without that information.

**Comment by blernermhc** [comment]
Works now that line numbers are recorded in ddg.txt.
