### ISSUE TITLE
Add preference to control look-and-feel

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/DDG-Explorer#32]
The look-and-feel is currently set to the WebLookAndFeel.  It would be good to add a command in the Preferences menu so the user can control whether to use that look-and-feel or the native look-and-feel.

**Comment by tfjmp** [comment]
Will do, the idea in the long run is to have something like this:
http://wiki.netbeans.org/NBLookAndFeels

**Comment by tfjmp** [comment]
See pull request #33
