### ISSUE TITLE
Consolidate ant command into a single build one?

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/DDG-Explorer#39]
Is there any rational behind the two steps?

```
ant build-project
ant ddg-explorer
```

**Comment by blernermhc** [comment]
The build file was created by Eclipse.  It looks like build-project is what gets used when you are running inside of Eclipse.  Notice how it has a debugging argument and only does the compilation, for example.

ddg-explorer builds the jar file that others can execute outside of Eclipse by double-clicking.

**Comment by tfjmp** [comment]
Yes, but do we want to keep it that way?

**Comment by blernermhc** [comment]
I don't think it matters to me.  I'll still be building inside Eclipse but it does not need the ant file to do that.
