### ISSUE TITLE
Include script numbers with line numbers in node labels

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/DDG-Explorer#40]
Script numbers are currently recorded in ddg.txt and ddg.json but are not displayed in node labels when the corresponding user preference is enabled. Suggest showing the script number (if not 0) followed by a colon and the line number (e.g. 1:3).

**Comment by blernermhc** [comment]
Changed in 3a740b38eb9a3eb5d1cf9b33968e3280583916b6.

With this change the user can see the script numbers, but the user cannot see the scripts themselves.  We need RDataTracker issue #134 to be addressed so we can do that.

**Comment by blernermhc** [comment]
This works now.
