### ISSUE TITLE
ddg.txt ending up in the database

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/DDG-Explorer#44]
See issue #37.

**Comment by blernermhc** [comment]
Partially fixed by a commit in RDataTracker:  d68c6042d4ba925086a88b979dd1998958fcec1d

That will keep ddg.txt from showing up as a script in the database.

We also need to update DDG Explorer so that it knows there is no script associated with the ddg.  That is not done yet.

**Comment by blernermhc** [comment]
Fixed by 70287782e6914e024f3da42b51c7dd35c74c3370
