### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by MatthiasHinz** [End-to-end-provenance/DDG-Explorer#51]
Hi, 

I just downloaded the RDatatracker and DDG-Explorer from the current and built/installed them both on my system (Ubuntu 16.04 LTS). When executing the first example script (see below), everything worked fine, but I can't display the ddg.txt, because I receive a NumberFormatException (see screenshot). 

Neither can I open any of the other generatet files with the explorer, but it works perfectly with the jar referenced in the following paper: 

https://www.mtholyoke.edu/~blerner/DataProvenance/UsingDDGExplorer.pdf
--> Jar: http://www.mtholyoke.edu/~blerner/DataProvenance/code/ddg-explorer.jar

I built the explorer with the following ant and java versions:
Apache Ant(TM) version 1.9.6

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Because I was wary, I repeated the procedure with the last release, which was just 16 days ago v2.7.0. Result was the same, only the number was different (0,044)

Yet a few weeks a go, I hat the same issue. If I remember correctly, I tried with a windows machine.

Is there maybe a recent jar available for download?
```
# Load the library.
> library(RDataTracker)

# Initialize DDG collection.
> ddg.init()

# Console session.
> x <- 3
> y <- 7
> z <- x + y

# Save the DDG
> ddg.save()
```

![ddg-explorer-error](https://cloud.githubusercontent.com/assets/2893162/17113425/08c10596-52ab-11e6-8f0b-0925fe63b07c.png)

**Comment by tfjmp** [comment]
Hi Matthias,

Could you upload the ddg.txt file for me to have a look?

Thanks!

**Comment by MatthiasHinz** [comment]
Of course! I will just upload the whole output. But a new file already.  The number displayed in the Exception is 4,292 now.

It seems like it corresponds to the time attribute in Operation p2, from the txt:

`Operation` p2 "2-x <- 3" Value="x <- 3" Time="4.292" Script="NA" Line="NA";

[ddg.zip](https://github.com/End-to-end-provenance/DDG-Explorer/files/382364/ddg.zip)

There might be more issues, as I can neither open any of the other files from the output... but well, at least the txt should work, I guess.

**Comment by tfjmp** [comment]
Can you confirm that you are using continental European number representation as your locale?
i.e. you use 2,45 vs 2.45 correct?

**Comment by MatthiasHinz** [comment]
Good question, I also wondered why the dot turned into a comma. But how can I do this? I am using de_DE.UTF-8 (Germany)

R sessionInfo gives me the following output

```
> > sessionInfo()
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.1 LTS
> 
> locale:
>  [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.1
```

and if y type 'locale' into the command shell, I get

```
locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by tfjmp** [comment]
I am not seeing "," in the ddg files you sent. Can you confirm that is the same on your local machine? If so it is a bug within DDG-Explorer.

**Comment by MatthiasHinz** [comment]
Confirmed. All numbers within the files have dots "." rather than commas ",". In particular the number '4.292' appears in the json and txt files.
On the other hand, the error message that appears in the Explorer says:

...NumberFormatException: For input string "4,292"
