### ISSUE TITLE
DDG Query "Display Execution Time of Operations"

### ISSUE THREAD

**Issue by alexsiqingliu** [End-to-end-provenance/DDG-Explorer#56]
DDG Query "Display Execution Time of Operations" doesn't show the individual execution time of each node, only shows a sorted list, see attached image:
<img width="997" alt="screen shot 2016-08-02 at 10 22 22" src="https://cloud.githubusercontent.com/assets/19556612/17331951/057c1fb0-589b-11e6-9df9-65ee24d9dcc1.png">

**Comment by blernermhc** [comment]
Implemented in https://github.com/End-to-end-provenance/DDG-Explorer/commit/2210bc03fdeb5d3a7d186d3cf33a88e268a22547
