### ISSUE TITLE
For some data nodes, the .csv files could not be found.

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/DDG-Explorer#60]
For example, when the following code is run (filename is `Test.R`):
```
a <- c()
a[1] <- 2
a[2] <- 3

i <- 1
b <- c()
b[i] <- 3

i <- 2
b[i] <- 4
```
In the ddg, when I try to view the value of variables `a` and `b`, it gives the following error:
```
File ~/./Test_ddg/8-b.csv does not exist.
```
The file is actually located:  `~/Test_ddg/data/8-b.csv`

**Comment by blernermhc** [comment]
This is an RDataTracker problem, not a DDG Explorer problem.  Data files are not stored in a data subfolder but the path name recorded in the provenance does not include the folder name.  I have created an issue for this on the RDataTracker side.
