### ISSUE TITLE
Path error for snapshot files

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/DDG-Explorer#63]
The version of DDG Explorer currently packaged with RDataTracker master and development is unable to display snapshot files (at least in Windows 7).  Right-clicking on a data node for a snapshot file returns a message of the form:

File C:/data/DDG/TEST/CalculateSquareRoot_ddg/./CalculateSquareRoot_ddg/data/37-sqr.root.csv does not exist.

**Comment by MKLau** [comment]
I also get this message when I am trying to view data that are stored as CSVs. 

![screen shot 2016-12-16 at 11 35 25 am](https://cloud.githubusercontent.com/assets/5342857/21270274/ef7cc972-c383-11e6-883e-bbd00fba03e2.png)

**Comment by blernermhc** [comment]
This was a problem in RDataTracker, not DDG Explorer.  It is fixed in commit ffc1741b38f2f58061b4595706aeb9f49010fa1b
