### ISSUE TITLE
Pipe representation

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/DDG-Explorer#80]
car_data <-
mtcars %>%
subset(hp > 100) %>%
aggregate(. ~ cyl, data = ., FUN = . %>% mean %>% round(2)) %>%
transform(kpl = mpg %>% multiply_by(0.4251)) %>%
print

**Comment by MKLau** [comment]
![screen shot 2017-01-31 at 5 27 53 pm](https://cloud.githubusercontent.com/assets/5342857/22487557/e350814e-e7db-11e6-9e03-82bcc6aa7d9b.png)

**Comment by MKLau** [comment]
Hi Barb, Emery and I chatted for a bit about this topic earlier today, so I worked up a little sketch to start the ball rolling.  When I use the **magrittr** example script, the left is what RDataTracker produces and DDG-Exp. displays currently. The right is what I'm thinking it would be useful to see. 

Also, I'm thinking it might be great to do something like having the left-side's "3-car_data <- mtcars..." node expand (right big blue arrow) to produce the right-side.

**Comment by tfjmp** [comment]
That's probably an issue in RDataTracker: https://github.com/End-to-end-provenance/RDataTracker/issues/236

**Comment by MKLau** [comment]
Hey Thomas, I think it's both. One issue is the DDG output (RDataTracker) and the other is the representation (DDG-E). I thought about but didn't add one to CamFlowR but I think we probably should.

**Comment by blernermhc** [comment]
This depends on rdt saving something different.
