### ISSUE TITLE
Vector graphics output 

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/DDG-Explorer#81]
For communications purposes, a scalable resolution graphics output, like PDF, could be really useful.

Understanding that some DDGs might be huge, setting an upper limit for the file size is probably going to be necessary.

Along that same track, having an option for using the current portion of the DDG viewed in the main window would also be useful.

**Comment by blernermhc** [comment]
This may not be so easy to do.  Vector graphics does not seem to be built in to Java.  There is a package at http://www.jibble.org/epsgraphics/ that looks promising, but it costs 40 pounds for a single user license and 500 pounds for an unlimited license.

**Comment by tfjmp** [comment]
RDataTracker is GPL3 https://github.com/End-to-end-provenance/RDataTracker/blob/master/LICENSE I do not believe it is going to be ok as far as licence is concerned.

**Comment by blernermhc** [comment]
I've found another package that looks promising and is free:
http://java.freehep.org/vectorgraphics/

**Comment by MKLau** [comment]
Yes, vector graphics would be awesome! But, holy-cow that color palette they chose is brutal!

**Comment by tfjmp** [comment]
They moved to github: http://freehep.github.io/freehep-vectorgraphics/

However, last commit is 3 years ago, this not maintained. We probably don't want to go that route.
