### ISSUE TITLE
Orphaned nodes move on ddg expansion

### ISSUE THREAD

**Issue by NullCGT** [End-to-end-provenance/DDG-Explorer#83]
I found that the orphaned nodes produced by RDataTracker that appear in DDG-Explorer (as mentioned [here](https://github.com/End-to-end-provenance/RDataTracker/issues/153)) move upward when a ddg is expanded. Strangely enough, this upward movement appears to be dependent on the current zoom. I was able to induce different amounts of movement (and sometimes no movement) depending on how far I was zoomed out. In addition, the orphaned node doesn't seem to appear on the overview screen until the tree is clicked at least once.

Github is currently not letting me upload the archive containing the ddg.json, but I was able to duplicate it and it does not seem file dependent.

**Comment by blernermhc** [comment]
I am more concerned that orphan nodes exist and that is an RDataTracker problem.  I don't think a valid ddg would ever have orphaned nodes, so I don't think this needs to be fixed.
